### DISCUSSION TITLE
Tracee, OPA, and WebAssembly (WASM) - as of May 2022

### DISCUSSION THREAD

**Discussion by danielpacak** [aquasecurity/tracee#1732] [Development]
## Summary

Based on my experiments with OPA WASM and wazero<sup>[1]</sup> runtime implementation I'd not recommend using it for high-throughput Tracee-Rules application. Mainly, because initial benchmark results<sup>[2]</sup> do not show significant improvements in comparison to OPA Go SDK. What's more, the implementation gets complex very quickly.

OPA is a powerful and generic tool for evaluating policies. However, there is a price to pay for such generic implementation in performance. Most of the Tracee-Rules signatures evaluate to simple boolean values. Using OPA, however, causes lots of objects on the heap to be created and decreases the overall processing speed. Beyond that, there's data serialization overhead whenever we cross WebAssembly runtime boundaries.

What we probably need is a less generic but more performant alternative. Notice also that some Tracee-Rules signatures do (document) transformation of the input event, but this functionality, for performance reasons, can be implemented in an imperative programming language after the policy is evaluated.

## Recommended Actions

1. Consider alternatives to OPA Rego as Domain Specific Language (DSL) to author signatures. For example, common expression language<sup>[3]</sup> can be used to write the Anti-Debugging signature as follows:
   ```
    input.EventName == 'ptrace' && arg(input, 'request') == 'PTRACE_TRACEME'
   ```
   The same or similar expression language can be used for filtering events in user-space and (maybe one day) in kernel.
2. (Optional) See how "All-in-one" OPA Rego policy evaluation performs with wazero in comparison to evaluating policies one by one.
2. (Optional) Follow up with OPA maintainers for more efficient ast.ParseTerm implementation that’s optimized for boolean Rego rules.

## Remarks
Even though we proved it’s possible to compile OPA Rego policy to WebAssembly module (WASM) and evaluate rules with a specified input event using wazero runtime<sup>[4]</sup>, this solution has a few drawbacks:
1. We are not solving the main performance problem in Tracee-Rules. We are moving it from OPA Go SDK somewhere else, i.e. wazero implementation.
2. The wazero runtime implementation is not feature complete. See, for example https://github.com/tetratelabs/wazero/issues/483
3. It's non trivial task to use WebAssembly / wazero API to write efficient signatures evaluation engine and success mainly depends on the upstream dependency implementation.

[1]: https://github.com/tetratelabs/wazero
[2]: https://github.com/danielpacak/webassembly-cookery-book/blob/main/anti-debugging-sig-wazero/signature/signature_benchmark_test.go
[3]: https://github.com/google/cel-spec
[4]: https://github.com/danielpacak/webassembly-cookery-book/blob/main/anti-debugging-sig-wazero/signature/signature.go

**Comment by danielpacak** [comment]
We further discussed alternatives to OPA Rego with @AsafEitani and here's a snippet of YAML that may be used to add expression-based signatures to Tracee-Rules. It's a rough idea, not a design:

```yaml
# tracee-config.yml

signatures:
  - metadata:
      id: "TRC -2"
      varsion: "0.1.0"
      name: "Anti-Debugging"
      description: "Process uses anti-debugging technique to block debugger"
      tags: ["linux", "container"]
      properties:
        "Severity": 3,
        "MITRE ATT&CK": "Defense Evasion: Execution Guardrails"
    eventSelector:
      - source: "tracee"
        name: "ptrace"
    expression: |
      input.EventName == 'ptrace' &&
        argument(input, 'request') == 'PTRACE_TRACEME'"
    outputData:
      foo: input.EventName
      bar: argument(input, "flags")
    outputTemplate: |
        // go template
    outputCommand: |
        // add example
```
