### DISCUSSION TITLE
Question: How to load custom rego rules into Kubernetes Daemonset?

### DISCUSSION THREAD

**Discussion by abhaybhargav** [aquasecurity/tracee#2402] [Questions and Help]
I have a basic question. I have checked across the documentation and the source code, but I am not able to figure this out. 

I have a few custom tracee rules (rego) that I'd like to load into my running kubernetes cluster. I have deployed tracee as a DaemonSet in my cluster. How do I load these custom rules into the tracee instance running on my Kubernetes cluster? 

Any help would be greatly appreciated

**Comment by josedonizetti** [comment]
@abhaybhargav Hey, sorry for the delay. Unfortunately, the experience to do it now isn't the best one, I'll create a task to make sure we improve it. So, what I did quickly here to make it work:

1 - created a configmap with my rule content

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracee-config
data:
  example_rule1.rego: |
    package tracee.ExampleRule1

    __rego_metadoc__ := {
      "id": "ExampleRule1",
      "version": "0.1.0",
      "name": "Example Rule 1",
      "description": "Process uses anti-debugging technique to block debugger",
      "tags": ["linux", "container"],
      "properties": {
        "Severity": 3,
        "MITRE ATT&CK": "Defense Evasion: Execution Guardrails",
      },
    }

    tracee_selected_events[eventSelector] {
      eventSelector := {
        "source": "tracee",
        "name": "ptrace",
      }
    }

    tracee_match {
      input.eventName == "ptrace"
      arg := input.args[_]
      arg.name == "request"
      arg.value == "PTRACE_TRACEME"
    }
```

2 - changed tracee daemonset to mount the configmap as a volume
```
volumeMounts:
        - mountPath: /rules
          name: tracee-rules

....
volumes:
      - configMap:
          name: tracee-config
        name: tracee-rules
```

3 - changed tracee daemonset to pass the path where the rules were mounted as an argument
```
containers:
      - args:
        - --rules-dir
        - /rules
```

There are probably different ways of doing it, but this should be fixed on the tracee side for a simpler experience. Like the trivy-operator does for defsec policies.

**Reply by abhaybhargav** [reply]
@josedonizetti in my case, my rego rule has an `import tracee.data.helpers` statement. Do i need to import the helpers rego or the go helpers code? And how would I do that? Another configmap?

**Reply by josedonizetti** [reply]
The simpler way of doing it would be consolidate all regos in the same configmap. So for the case where you have the tracee helper, plus other rules, it would look like:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracee-config
data:
  helpers.rego: |
   .... content for tracee-helpers
  your_rule1: |
  .....
  your_rule2: |
  ...
```

So, when this configmaps mount, the directory will have one file per key.
