### DISCUSSION TITLE
Tracee Policies

### DISCUSSION THREAD

**Discussion by yanivagman** [aquasecurity/tracee#2640] [Development]
Now that we have sets of filters in place, we can move to the next step of implementing runtime policies in tracee.
Following is a proposal for how we can implement policies in Tracee. Any comments/suggestions are welcome.

A runtime policy is composed of:

- Policy Name
- Description
- Scope (on which the policy will be applied)
- Rules list, where each rule have:
    - event trigger
    - specific filters for event context/arguments (optional)
    - actions - TBD (optional)

Policies will be defined in files - one policy per file
A policy can be given to tracee using a new "--policy" flag, which takes the path of the policy as an argument

Following is an example for such a policy, defined in a yaml file:

```
name : new_containers
description: “This policy will be applied on any new container created in the system”
scope:
      - container=new
      - binary!=/usr/bin/dockerd,/usr/bin/runc
defaultAction: log             # (/webhook/block/kill)
rules:
    - event:security_file_open
      filter:
          - uid=1000
          - arg.pathname=/tmp/a,/etc/passwd
          - arg.pathname!=/tmp/exception    # longest prefix wins!
          - arg.flags=O_CREAT
      action:
          - webhook
      # in the future, we may support more than one rule per event type
    - event: anti-debugging
      filter:
          - comm!=gdb,strace
          - binary=/whatever
      # if no action is given - default action is taken
    - event: net_packet_ipv4:
      filter:
          - traffic=ingress
          - protocol=tcp
          - dst.port=80
      action:
          - block
    - event: process_exec
      filter:
          - comm=bash
      action:
          - block
          - webhook:
              url: sdfdsf.com
          - log:
              format: pathname
              # TBD: format usage
```

**Comment by itaysk** [comment]
it would be helpful to consider how policy maps to current cli flags. let me know if I get it right or I missed something:

`--trace <event.context.something>=` --> entry in `scope`
`--trace binary, tree, follow?` => entry in `scope`
`--trace event=` --> entry in `events`
`--trace <event.args.something>=` --> entry in event under `events`

not sure how to place `event=something*` and `set=`.

**Reply by NDStrahilevitz** [reply]
I think `set` could map to a string list of automatically included event which you don't want to specify entires for. Otherwise it can just not be included in a policy.
`event=something*` should probably stay a cli thing.

**Reply by yanivagman** [reply]
> `--trace <event.context.something>=` --> entry in `scope`

Actually this is also an entry in event under `events`


> not sure how to place `event=something*` and `set=`

Agree with @NDStrahilevitz it should probably stay a cli thing.

**Reply by itaysk** [reply]
> Actually this is also an entry in event under events 

ok, so how do we define what is in scope and what is in event? (categorically, not by example)

**Reply by NDStrahilevitz** [reply]
> ok, so how do we define what is in scope and what is in event? (categorically, not by example)

The difference is between, "I only want this filter on this event (context filter)" and "I want this filter applied globally (as a scope)".

**Reply by itaysk** [reply]
ok, so all filters are available in both scope and event? and the difference is their affect being global or just for the event?

**Reply by yanivagman** [reply]
This is true for context filters.
Event also has argument filters, so it cannot be applied in scope

**Reply by itaysk** [reply]
We talked and Yaniv put it clearly to me as: `scope` is for choosing the workload, and `events` is for choosing the events.

**Comment by itaysk** [comment]
I'm not sure about the way operators are declared. in your example:

```
- anti-debugging:
                comm:
                    not_equal:  
                      - gdb
                      - llvm-gdb
```

^^ here we use `not_equal` to operate.

```
     - security_file_open:
              argument.pathname:
                  - /tmp/*
```

^^ here I suppose it's implicitly "equal" but then the value contains a modifier `*`

```
    - net_packet_ipv4:
              protocol:
                  tcp
```

^^ here there's no operator at all

Additionally, the `scope` section ignores operators but there might be there as well?

I'm thinking maybe to just use the same operators we have today in the cli? It's more readable for the user and probably will be easier to implement since the code is already there.

So it will look like:

```
events:
     - security_file_open:
              filter: 
                  - argument.pathname=/tmp/*
     - anti-debugging:
              filter:
                  - comm!=gdb
                  - comm!=llvm-gdb
    - net_packet_ipv4:
             filter: 
                  - protocol=tcp
                  - port-80
              action:
                  - block  
```

alternatively, if we want structured operators then we need to 1) use them more consistently across the yaml 2) make sure all current and future ones are easily supported
