### DISCUSSION TITLE
Prepare for v0.18.0

### DISCUSSION THREAD

**Discussion by itaysk** [aquasecurity/tracee#3531] [Development]
# 🚨 Breaking changes 🔨

Tracee policies `apiVersion` and `kind` were renamed.

eg:

```
apiVersion: tracee.aquasec.com/v1beta1
kind: Policy
metadata:
  name: dig
  annotations:
    description: traces dns events from the dig binary
spec:
  scope: 
    - binary=/usr/bin/dig
  rules:
    - event: net_packet_dns_request        
    - event: net_packet_dns_response
```

# 🚀 What's new? 🚀

## 💡 New GRPC API (Experimental) ☎️

Tracee now has a fully functional beta GRPC API. The following operations are supported with more coming in the future:

  - Consume events using GRPC stream
  - Enable/Disable events
  - Diagnostics & Logging
  - Performance Counters

Note that events by the GRPC API follow a [new event structure]() which isn't compatible with the older event structure. In future versions of Tracee this new structure will replace the older one for all other interactions.

## 🗃️ Process Tree 🌲

Tracee now maintains **live representation of the system processes tree**. This information is exposed to signatures through the **datasource mechanism** (a mechanism that allows golang signatures to access data collected by tracee events).

* An example on how this feature can be used, by a signature event, can be found [HERE](https://gist.github.com/rafaeldtinoco/ddb06a57aa835d0df3d9343e1db87af4).

## 📩 Events / Signatures ⚡️

- New event: ftrace_hook (#3412)
- Add `argv` to `security_bprm_check` (#3442)

## 🦄 Misc 💐

- Filter file capture by ELF type (#3361)

# 🔨 Fixes 👷

- fix(ebpf): triggerMemDump check all filters (#3504)
- fix(packaging): adjust ubuntu and fedora packaging (#3502)
- fix: stackaddress needs to have symbol name
- fix(event): enable ksymbols engine for PrintMemDump (#3443)
- Fix(capture): fix verifier issue with elf capture (#3433)
- fix: fix section name for vfs_readv (#3421)
- fix: capture of writev (#3413)
- fix: ignore error for cgroups that doesn't exist
- fix: log level should match zap log priority
- fix: k8s policies tutorial
- fix(cmd): --help flag parsing
- fix(capture): remove CONFIG_KALLSYMS_ALL dependency (#3381)
- fix(config): loading config file
- fix(flags)!: del help cmd, add md files for flags (#3321)
- fix: validate policy names are rfc 1123 (#3335)
- fix(ebpf): size of mntns/pidns filters key holders (#3337)
- feature:(ebpf): don't fail on probe attachment err
