### ISSUE TITLE
Suggestion - Add toleration to daemonset manifest

### ISSUE THREAD

**Issue by raesene** [aquasecurity/tracee#1035]
In the Kubernetes [daemonset manifest](https://github.com/aquasecurity/tracee/blob/main/deploy/kubernetes/tracee.yaml) there's no tolerations for common taints. As a result the daemonset won't schedule pods to control plane nodes (or any other node with a taint on it).

Something like the below could be added to the daemonset to ensure that it tolerates all taints.

```
  tolerations:
  - operator: "Exists"
    effect: "NoExecute"
  - operator: "Exists"
    effect: "NoSchedule"
```
