### ISSUE TITLE
[BUG] Missing Pod Information from Container Labels

### ISSUE THREAD

**Issue by fjogeleit** [aquasecurity/tracee#1786]
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [ ] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [x] Someone else should solve this.

## Bug description

This is how I'm executing tracee (cmdline):

I am using Kubernetes to run tracee as DaemonSet, I used the following configuration:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: tracee
    app.kubernetes.io/component: tracee
    app.kubernetes.io/part-of: tracee
  name: tracee
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tracee
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tracee
      name: tracee
    spec:
      containers:
      - name: tracee
        image: docker.io/aquasec/tracee:full-dev
        imagePullPolicy: Always
        args:
          - --output-template /tracee/templates/rawjson.tmpl
        env:
          - name: LIBBPFGO_OSRELEASE_FILE
            value: /etc/os-release-host
        securityContext:
          privileged: true
        volumeMounts:
        - name: etc-os-release
          mountPath: /etc/os-release-host
          readOnly: true
        - name: modules
          mountPath: /lib/modules
          readOnly: true
        - name: src
          mountPath: /usr/src
          readOnly: true
        - name: socket
          mountPath: /var/run/containerd
          readOnly: true
        resources:
          limits: {}
          requests:
            cpu: 350m
            memory: 50Mi
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
      - hostPath:
          path: /etc/os-release
        name: etc-os-release
      - hostPath:
          path: /usr/src
        name: src
      - hostPath:
          path: /lib/modules
        name: modules
      - hostPath:
          path: /run/k3s/containerd
        name: socket
```

Environment:
Kubernetes Distribution: k3s
Kubernetes Version: v1.23.3+k3s1
Container Runtime: containerD
ContainerD Version: v1.5.9-k3s1

What I tried:

Installed tracee with the configuration above. I mounted the containerd socket at the path mentioned in the code: https://github.com/aquasecurity/tracee/blob/main/cmd/tracee-ebpf/internal/flags/flags-containers.go#L17

I found that additional information could be get in debug mode but I was not able to enable debugging with the provided container image. I also found the `containers` flag to set the runtime and path manually but also this was not possible to configure.

Steps to reproduce the issue:

- Install tracee as DeamonSet
- Run a nginx via `kubectl run nginx --image nginx`
- Install and exec strace inside the nginx 
  - `kubectl exec -it nginx -- apt-get update`
  - `kubectl exec -it nginx -- apt-get install -y strace`
  - `kubectl exec -it nginx -- strace ls`

The produced Event JSON contains keys for podName, podNamespace and podUID but they are empty. I would expect that the information are available.

Example Event:

```json
{
  "Data": null,
  "Context": {
    "timestamp": 1653227866340306400,
    "processorId": 3,
    "processId": 485,
    "threadId": 485,
    "parentProcessId": 483,
    "hostProcessId": 2138888,
    "hostThreadId": 2138888,
    "hostParentProcessId": 2138886,
    "userId": 0,
    "mountNamespace": 4026534304,
    "pidNamespace": 4026534305,
    "processName": "strace",
    "hostName": "nginx",
    "containerId": "",
    "eventId": "101",
    "eventName": "ptrace",
    "argsNum": 4,
    "returnValue": 0,
    "stackAddresses": null,
    "args": [
      {
        "name": "request",
        "type": "string",
        "value": "PTRACE_TRACEME"
      },
      {
        "name": "pid",
        "type": "pid_t",
        "value": 0
      },
      {
        "name": "addr",
        "type": "void*",
        "value": "0x0"
      },
      {
        "name": "data",
        "type": "void*",
        "value": "0x0"
      }
    ]
  },
  "SigMetadata": {
    "ID": "TRC-2",
    "Version": "0.1.0",
    "Name": "Anti-Debugging",
    "Description": "Process uses anti-debugging technique to block debugger",
    "Tags": [
      "linux",
      "container"
    ],
    "Properties": {
      "MITRE ATT&CK": "Defense Evasion: Execution Guardrails",
      "Severity": 3
    }
  }
}
```
