### ISSUE TITLE
problem filtering args of type 'bytes'

### ISSUE THREAD

**Issue by roikol** [aquasecurity/tracee#3110]
## Description

in previous versions of tracee i was able to filter arguments of type `bytes` like so:

`./dist/tracee-ebpf -f e=magic_write -f magic_write.args.bytes="[11 11*,[22 22*,[33 33*"`

when trying to do the same thing using policies, the event is not triggered at all.

policies i've tried (difference is the `""`):

```
name: test policy
description: test magic_write filter
scope:
  - global
defaultAction: log
rules:
  - event: magic_write
    filter:
      - args.bytes="[11 11*,[22 22*,[33 33*"
```

```
name: test policy
description: test magic_write filter
scope:
  - global
defaultAction: log
rules:
  - event: magic_write
    filter:
      - args.bytes=[11 11*,[22 22*,[33 33*
```

* for the sake the example i gave a simple psuedo filter (`[11 11*,[22 22*,[33 33*`). 
  i can provide the real filter we use if needed

## Output of `tracee version`:

```
(paste your output here)
```

Tracee version: "v0.14.2"
