### ISSUE TITLE
policy: error processing policy with arguments

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#3143]
## Description

```
sudo ./dist/tracee -p test.yaml
Error: policy.validateContext: policy openat_args_pathname, filter args.pathname is not valid
```

```
name: openat_args_pathname
description: traces openat under /tmp/*
scope:
  - global
defaultAction: log
rules:
  - event: openat
    filter:
      - args.pathname=/tmp*
```
## Output of `tracee version`:

```
(paste your output here)
```

## Output of `uname -a`:

```
(paste your output here)
```
