### ISSUE TITLE
parsing policy with "!=" filter

### ISSUE THREAD

**Issue by roikol** [aquasecurity/tracee#3166]
## Description

there's an error occuring when trying to filter out an argument using the policies.

the error:

`Error: policy.validateEventArg: policy test policy, event symbols_loaded does not have argument library_path!`

the policy:

```
name: test policy
description: test symbols_loaded filter
scope:
  - global
defaultAction: log
rules:
  - event: symbols_loaded
    filter:
      - args.library_path!=libc
```

## Output of `tracee version`:

```
(paste your output here)
```

## Output of `uname -a`:

```
(paste your output here)
```
