### ISSUE TITLE
policy should support multiple actions

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#3174]
```
name: policy1
description: policy1
scope:
  - global
defaultAction: 
  - log
  - webhook:http://localhost:8080
rules:
  - event: anti_debugging
    action: webhook:http://localhost:8080
  - event: openat
    filter:
      - args.pathname=/tmp/lua*
     action:
      - log
      - webhook:http://localhost:8080
```
