### ISSUE TITLE
support yaml arrays for argument filters in policy files

### ISSUE THREAD

**Issue by roikol** [aquasecurity/tracee#3180]
currently, in order to have multipile values in the same argument filter in policy file, we separate them by commas:

```
  - event: security_file_open
    filter:
      - args.pathname=aaaaaaaaaaaaaaaaaaaa*,bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb*,
        cccccccccccccccccccccccccccccccccccccccccccccccccc*
```

this causes issues with parsing the policy files.

we want to use yaml arrays for that.

for example:
```
  - event: security_file_open
    filter:
      - args.pathname:
          - aaaaaaaaaaaaaaaaaaaa*
          - bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb*
          - cccccccccccccccccccccccccccccccccccccccccccccccccc*
```
