### ISSUE TITLE
policies: rename  scope, filter and action to use plural as they are arrays

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#3181]
```
name: sample
description: sample
scopes: 
  - global
rules:
  - event: name
     filters:
        - retval=0
        - args.pathname!=/tmp
     actions:
        - webhook
        - log
```
