### ISSUE TITLE
structured config file 

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#3182]
Currently, several elements of the configfile are configured like flags with strings, it would be good to have a structure, for example, instead of

```
output:
    - webhook:HTTP://localhost:8080?timeout=5
```

we had

```
output:
    - webhook:
          url: http://localhost:8080
          timeout=5
```

the same for other elements, for webhook we could use it to support alias so the user can use different wehooks on his policies

```
output:
    - webhook:
         name: webhook1
          url: http://localhost:8080
          timeout=5
   - webhook:
         name: webhook2
          url: http://localhost:8081
          timeout=5
```

**Comment by geyslan** [comment]
Those options are bound to viper, so in order to bring the structured options and keep the old way of passing string flags (similar to cli flags), we must rely on type coercion to detect if the `output` options (in this example) are set as legacy or structured.

We have all these that can be structured:

```yaml
cache:           # [type|mem-cache-size]
    - none
proctree:        # [process|thread]
    - none
capabilities: [] # [bypass|add|drop]
crs: []          # <runtime:socket>
log:             # [debug|info|warn...]
    - info
output:          # [json|none|webhook...]
    - json
rego: []         # [partial-eval|aio]
```

For each one, we should do type checks and try to detect if it's legacy (string) or structured.

So, to not touch in so much code right now I ask if the following approach (add option-structured) should be a fit:

```yaml
output:
    - webhook:HTTP://localhost:8080?timeout=5s
output-structured:
    - webhook:
        name: webhook1
        host: http://localhost
        port: 8000
        timeout: 5s
    - webhook:
        name: webhook2
        host: http://localhost
        port: 9000
        timeout: 5s
```
