### ISSUE TITLE
config yaml file can't set output to json

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#3186]
## Description

When using the following config file:

```yaml
blob-perf-buffer-size: 1024
install-path: /tmp/tracee
cache:
    - cache-type=mem
    - mem-cache-size=1024
capabilities: []
containers: true
crs: []
log:
    - info
output:
    - json
perf-buffer-size: 1024
pyroscope: false
rego: []
signatures-dir: ""
metrics: true
healthz: true
pprof: true
listen-addr: :3366
```

and executing

```
sudo ./dist/tracee --config ~/policies/config.yaml 
```

Tracee output isn't json as expected (should it be ?)

## Output of `tracee version`:

```
commit: 234b9d0d
```

## Output of `uname -a`:

```
v6.3.0
```

## Additional details 

![image](https://github.com/aquasecurity/tracee/assets/7395852/a29e3f57-f52e-4854-b95f-ebab6d33ff2d)
