### ISSUE TITLE
signatures with filtered base events not triggered

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#3207]
## Description

```

name: signature_events

description: traces all signature events

defaultAction: log

scope:

  - global

rules:

  - event: ptrace

    filter:

      - userId=1000

  - event: anti_debugging

```

## Output of `tracee version`:

```
(paste your output here)
```

## Output of `uname -a`:

```
(paste your output here)
```
