### ISSUE TITLE
Policy load is not setting rules filters

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/tracee#3218]
## Description

Policy file loading isn't setting rules filters like:

https://github.com/aquasecurity/tracee/blob/main/examples/policies/pid_equal.yaml

```yaml
name: pid_equal
description: traces read and write syscalls for pids 1000, and 2000
scope: 
  - global
defaultAction: log
rules:
  - event: read
    filter: 
      - pid=1000
  - event: write
    filter:
      - pid=2000
```

`sudo ./dist/tracee -p ./examples/policies/pid_equal.yaml`

Debug printfs:

```
...
====== bitmap: 00000001, eventName: write, comm: gdbus, pid 2730
====== bitmap: 00000001, eventName: read, comm: gdbus, pid 2730
====== bitmap: 00000001, eventName: read, comm: gdbus, pid 2730
====== bitmap: 00000001, eventName: write, comm: gdbus, pid 2730
...
```

`sudo bpftool map dump name pid_filter`

```
[]
```

I have also tested with `comm` and `uid` filters and can confirm that the related maps aren't being populated from filters set in the policy file rules.

However, filters seems to work when set in scope, as in:

https://github.com/aquasecurity/tracee/blob/main/examples/policies/scope_comm.yaml

```yaml
name: comm_strace
description: traces sched_process_exec and sched_process_exit for the command strace
scope: 
  - comm=strace
defaultAction: log
rules:
  - event: sched_process_exec
  - event: sched_process_exit
```

`sudo bpftool map dump name comm_filter`

```json
[{
        "key": {
            "str": "strace"
        },
        "value": {
            "equal_in_scopes": 1,
            "equality_set_in_scopes": 1
        }
    }
]
```

## Output of `tracee version`:

`main`

## Output of `uname -a`:

`Linux hb 6.1.31-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Jun  4 12:31:46 UTC 2023 x86_64 GNU/Linux`

## Additional details 

The expected behaviour can be seen by cli (in this case just for one event):

`sudo ./dist/tracee -f e=read -f pid=1000`
`sudo bpftool map dump name pid_filter`

```json
[{
        "key": 1000,
        "value": {
            "equal_in_scopes": 1,
            "equality_set_in_scopes": 1
        }
    }
]
```
