### ISSUE TITLE
policies: make defaultAction a list

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#3241]
```
name: dig
description: traces dns events from the dig binary
scopes: 
  - binary=/usr/bin/dig
defaultActions: 
  - log
rules:
  - event: net_packet_dns_request        
  - event: net_packet_dns_response
```
