### ISSUE TITLE
derived events not triggering for filtered base events

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#3279]
eg: 

```yaml
name: pol1
description: general policy
scope:
  - global
defaultActions: 
  - log
rules:
  - event: cgroup_mkdir
    filter:
      - args.cgroup_path!=/system.slice*
  - event: container_create
```
