### ISSUE TITLE
add policy version

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#3320]
Let's add version to policy files. This will allow us to extend policies while keeping backward compatibility when necessary.

 
```

version: v1beta1
name: dig
description: traces dns events from the dig binary
scope: 
  - binary=/usr/bin/dig
rules:
  - event: net_packet_dns_request        
  - event: net_packet_dns_response

```

**Comment by itaysk** [comment]
I'd say try keeping it compatible with k8s scheme, since policy is a strong candidate to become a CRD some day. 
Having said that, full k8s compatibility will require the following wrapping, which is more than the scope of this issue, but we can still make choices the will move us closer to this goal:

```yaml
apiVersion: tracee.aquasec.com/v1beta1
kind: Policy
metadata:
  name: dig
  description: traces dns events from the dig binary
spec:
  scope: 
    - binary=/usr/bin/dig
  rules:
    - event: net_packet_dns_request        
    - event: net_packet_dns_response
```
