### ISSUE TITLE
Tutorial "Working with Tracee Policies on Kubernetes" ConfigMap out of date

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/tracee#3368]
https://aquasecurity.github.io/tracee/v0.17/tutorials/k8s-policies/

The tutorial says to add the following block of YAML to the ConfigMap:

```
events.yaml: |-
  apiVersion: aquasecurity.github.io/v1beta1
  kind: TraceePolicy
  metadata:
      name: execve-event
      annotations:
        description: traces all signature events
  spec:
      scope:
        - global
      rules:
        - event: execve
```

after the `signatures.yaml`

This structure is a bit unclear as I would have added it as a separate file as such:
```
Name:         tracee-policies
Namespace:    tracee-system
Data
====
signatures.yaml:
---
events.yaml: |-
  apiVersion: aquasecurity.github.io/v1beta1
  kind: TraceePolicy
  metadata:
      name: execve-event
      annotations:
        description: traces all signature events
  spec:
      scope:
        - global
      rules:
        - event: execve
 --- (the rest of the existing file below)
apiVersion: aquasecurity.github.io/v1beta1
kind: TraceePolicy
metadata:
    name: signature-events
    annotations:
        description: traces all signature events
spec:
    scope:
      - global
    rules:
      - event: stdio_over_socket
      - event: k8s_api_connection
      - event: aslr_inspection
      - event: proc_mem_code_injection
      - event: docker_abuse
      - event: scheduled_task_mod
      - event: ld_preload
      - event: cgroup_notify_on_release
      - event: default_loader_mod

```

However, looking at @josedonizetti's example, this is not how you meant it? 
https://gist.githubusercontent.com/josedonizetti/3df19a61d39840441ea5be448d6c9354/raw/c50b9b66d7996bb27b6fac301d24d6390e356f8c/tracee-policies-configmap.yaml
