### ISSUE TITLE
docs: syscalls as Tracee events

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/tracee#3403]
Just to clarify, I can use syscalls as events in the Tracee Policy?

e.g. https://aquasecurity.github.io/tracee/v0.17/docs/events/builtin/syscalls/open/

```
spec:
    scope:
      - container
    rules:
      - event: open
```

**Comment by geyslan** [comment]
Yep, take a look at [examples/policies/openat_args_pahtname.yaml](https://github.com/aquasecurity/tracee/blob/main/examples/policies/openat_args_pahtname.yaml)

```
❯ cat examples/policies/openat_args_pahtname.yaml
apiVersion: aquasecurity.github.io/v1beta1
kind: TraceePolicy
metadata:
  name: openat-args-pathname
  annotations:
    description: traces openat under /tmp/*
spec:
  scope: 
    - global
  rules:
    - event: openat
      filters:
        - args.pathname=/tmp*
```
