### ISSUE TITLE
docs: modifying Tracee Policies

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/tracee#3404]
Question: Do all new Tracee Policies have to be added directly to the Tracee ConfigMap as detailed in the tutorial? If I have 64 Policies that would make the file very long.

It's detailed to add all Policies to the `data` section in the ConfigMap:
```
kubectl get configmap/tracee-policies -n tracee-system -o yaml     
apiVersion: v1
data:
  signatures.yaml: |-
```

From a user experience perspective, it would be much nicer to just apply the Policy directly to the tracee-system namespace: traceepolicyone.yaml
```
apiVersion: aquasecurity.github.io/v1beta1
    kind: TraceePolicyOne
    metadata:
      name: syscall-events
      namespace: tracee-system
      annotations:
        description: traces all signature events
    spec:
      scope:
        - global
      rules:
        - event: open
```
and then 

```
kubectl apply -f traceepolicyone.yaml -n tracee-system
```
