### ISSUE TITLE
Tracee doesn't log events on open file

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/tracee#3405]
I am on Kubernetes v1.27.1 on Azure Kubernetes Service.
I deployed the following policy to the Tracee Policy inside the ConfigMap:
```
  apiVersion: aquasecurity.github.io/v1beta1
  kind: TraceePolicy
  metadata:
    name: syscall-events
    namespace: tracee-system
    annotations:
      description: traces open syscall events
  spec:
    scope:
      - container
    rules:
      - event: open
      - event: file_modification
```
I basically want to log an event whenever a file is opened inside my nginx container. 
The nginx container is running as a 2 replica set deployment inside the demo namespace. 

I then went ahead, edited the ConfigMap, restarted the Tracee daemonset as described in the Policy tutorial and then opened random files inside the container (I sshed into one of the nginx containers and called cat but I was thinking that files also should be opened if I simply port-forward the nginx service, no?). However, the only logs I get are the following -- is Tracee running correctly? 

```
❯ kubectl logs ds/tracee -n tracee-system 

Found 2 pods, using pod/tracee-skk6r
{"level":"warn","ts":1692703572.6543858,"msg":"KConfig: could not check enabled kconfig features","error":"could not read /boot/config-5.15.0-1042-azure: stat /boot/config-5.15.0-1042-azure: no such file or directory"}
{"level":"warn","ts":1692703572.654583,"msg":"KConfig: assuming kconfig values, might have unexpected behavior"}
```

How can I test Policies? I mean I first have to make sure that Tracee has my Policy correctly

**Comment by AnaisUrlichs** [comment]
Update, there is also nothing when I use the Policy from the tutorial so I am not sure how I can understand where the issue is? https://aquasecurity.github.io/tracee/v0.17/tutorials/k8s-policies/

**Comment by josedonizetti** [comment]
Can you check which Tracee version you are using? There was a [bug](https://github.com/aquasecurity/tracee/pull/3375) on 0.17.0 that affected kubernetes installation, so make sure you running 0.17.1. 

If you running 0.17.1, can you change tracee to its default, and test it to see if you get events, a simple way is to trigger a `strace ls` from another container, which should trigger the `anti_debugging`  signature.

**Comment by AnaisUrlichs** [comment]
Probably should have done that before experimenting around :D 

the ConfigMap has the following labels:
```
  labels:
    app.kubernetes.io/instance: tracee
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tracee
    app.kubernetes.io/version: 0.17.1
    helm.sh/chart: tracee-0.17.1
```

will try strace now
