### ISSUE TITLE
Tracee is tracing itself on k8s when it shouldn't

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#3645]
## Description

When deploying tracee as a daemonset, at least in microk8s, I'm getting false positives during the daemonset startups:

![image](https://github.com/aquasecurity/tracee/assets/7395852/6d62c7c4-e0c0-4629-8666-de0b019532c8)

You can see that tracee was the one that originated the events that caused the signatures to be triggered. And they're related to things such as opening the docker socket, for example.

## Output of `tracee version`:

```
v0.18.1 and latest
```

## Output of `uname -a`:

```
Linux rugged 6.1.60-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 25 Oct 2023 11:10:15 +0000 x86_64 GNU/Linux
```

## Additional details 

I believe that, maybe, tracee isn't populating its PID in the map that serves eBPF code not to tracee itself only after initialization already causes those events (or something similar).

**Comment by rafaeldtinoco** [comment]
A mitigation:

If tracee uses ConfigMap for the policies, then change the default ConfigMap `tracee-policies` not to tracee the binary:

```yaml
apiVersion: v1
data:
  signatures.yaml: |-
    apiVersion: tracee.aquasec.com/v1beta1
    kind: Policy
    metadata:
      name: signature-events
      annotations:
        description: traces all signature events
    spec:
      scope:
        - comm!=tracee
      rules:
        - event: stdio_over_socket
        - event: k8s_api_connection
        - event: aslr_inspection
        - event: proc_mem_code_injection
        - event: docker_abuse
        - event: scheduled_task_mod
...
```
