### ISSUE TITLE
Easy way to enable all signatures in a policy

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#3751]
Currently, if a user loads a shared object with a large amount of sigantures, the work of actually enabling all these signatures is exhausting (imagine writing 50 different sigantures and enabling all of them!).
The likely way to implement this is supporting sets again or something similar in the policy file. So we could do something like
```
...
spec:
    scope:
        - global
    rules:
        set: signatures
        event: security_file_open
```

**Comment by yanivagman** [comment]
If we're going to support this, let's use the term tags and not sets since we're going to consolidate signature tags and event sets as part of the move to "everything is an event" architecture

**Comment by yanivagman** [comment]
And maybe just call it `events`?

```
spec:
    scope:
        - global
    rules:
        event: security_file_open
        events: signatures

```
