### ISSUE TITLE
tracee can't load webhook config when not using an URL

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#3866]
```
Error: printer.(*webhookEventPrinter).Init: unable to convert timeout value "5s?gotemplate=/path/to/template/test.tmpl?contentType=application/json": time: unknown unit "s?gotemplate=/path/to/template/test" in duration "5s?gotemplate=/path/to/template/test.tmpl?contentType=application/json"
```

```
cache:
    type: mem
    size: 512
perf-buffer-size: 1024
healthz: true
metrics: true
pprof: false
pyroscope: false
listen-addr: :3366
log:
    level: info
output:
    json:
        files:
            - stdout
    options:
        parse-arguments: true
        stack-addresses: false
        exec-env: false
        relative-time: true
        exec-hash: dev-inode
        sort-events: false
    webhook:
        - webhook1:
            protocol: http
            host: 10.0.0.20
            port: 8080
            timeout: 3s
            gotemplate:
            content-type: application/json
```
