### ISSUE TITLE
Implement flag parsing for Server.

### ISSUE THREAD

**Issue by ShohamBit** [aquasecurity/tracee#4473]
Imapmaent the new design for the server flag as described:

```[tasklist]
### Tasks
- [x] Implement HTTP flags
- [x] Implement gRPC flag
- [x] Document new flag design
- [x] Test new flag design
```

The following design describes the CLI flag:
```
--server http.metrics=<true/false>        # Enable metrics endpoint
--server http.pprof=<true/false>          # Enable pprof endpoints
--server http.healthz=<true/false>       # Enable health check endpoint
--server http.pyroscope=<true/false>  # Enable Pyroscope agent
--server http.address=<address>        # Set HTTP server listening address
--server grpc.address=<address>       # Set gRPC server listening address
```

The following design describes the config:

```
server:
  http:
    metrics: false   # Enable metrics endpoint
    pprof: false     # Enable pprof endpoints
    healthz: false   # Enable health check endpoint
    pyroscope: false # Enable Pyroscope agent
    address: ":3366" # Set HTTP server listening address (default ":3366")
  grpc:
    address: ""      # Set gRPC server listening address (default: disabled)
```
