### ISSUE TITLE
Events set doesnt work

### ISSUE THREAD

**Issue by stasos24** [aquasecurity/tracee#4706]
## Description

Run tracee with policy

```
apiVersion: tracee.aquasec.com/v1beta1
kind: Policy
metadata:
    name: sample-policy
    annotations:
        description: traces execve events
spec:
    scope:
      - global
    rules:
      - event: syscalls
```

## Output of `tracee version`:

```
Tracee version: v0.23.1
```

## Output of `uname -a`:

```
Linux localhost 6.1.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1kali2 (2023-02-23) x86_64 GNU/Linux
```
